version: "2"

services:
  db:
    environment:
      POSTGRES_DB: pets_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      
    restart: always
    image: postgres:12
    expose:
      - "5432"

  webserver:
    environment:
      DJANGO_MANAGEPY_MIGRATE: "on"
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_HOST: db
      REDIS_HOST: redis

    command: ['python', 'manage.py', 'runserver', '0.0.0.0:8000']


    image: deepaknair/pets-app
    links:
      - db:db
      - redis:redis
    ports:
      - "8000:8000"


  redis:
    image: redis
    ports:
      - "6379:6379"
