apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: django-hpa
spec:
  maxReplicas: 10
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: django
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 50